/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

extern void initialise_monitor_handles(void);

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
	initialise_monitor_handles();

	printf("The size of char data type is %u\n",sizeof(char));
	printf("The size of int data type is %u\n",sizeof(int));
	printf("The size of short data type is %u\n",sizeof(short));
	printf("The size of double data type is %u\n",sizeof(double));
	printf("The size of Long data type is %u\n",sizeof(long));
	printf("The size of long long data type is %u\n",sizeof(long long));
    /* Loop forever */
	for(;;);
}
